language: python
sudo: false

env:
  global:
    - secure: "Zmj7rrKx4z3JyaKNJUzILhMSESf7tCPBt9ad67veaX+fwYlJzrHUq+iy+5RXSye/g3vpsfehpKs/F2bAQcmX1ysLDOvd8w+UvwQPRi/GXxvVn7CHD6C4rpiSJAJHbCk7FZwQlo8P6VE8qiqUMCJcXjnjl63egkvJlkl6+rbE00E="
  include:
    - python: 3.5
      env:
        - TOX_ENV=py35
  fast_finish: true

env:
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pyflakes
  - TOX_ENV=cov
  - TOX_ENV=docs
  - TOX_ENV=apidocs
  - PUSH_DOCS=true

install:
  - pip install tox

script:
  - if [[ -n "${TOX_ENV}" ]]; then tox -e $TOX_ENV; fi
  - if [[ "$PUSH_DOCS" == "true" ]]; then ./.travis/build_docs.sh; fi

notifications:
  email: false
